# Generated by Django 5.0.3 on 2026-05-08 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("increasing", "Increasing"),
                            ("decreasing", "Decreasing"),
                            ("stable", "Stable"),
                            ("volatile", "Volatile"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_change_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage change (positive or negative)",
                        max_digits=6,
                    ),
                ),
                ("average_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "volatility_index",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0-100, higher = more volatile",
                        max_digits=5,
                    ),
                ),
                (
                    "forecast_next_period",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Trend",
                "verbose_name_plural": "Price Trends",
                "db_table": "price_trends",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("district", models.CharField(max_length=100)),
                ("price_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_avg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                ("currency", models.CharField(default="ZWL", max_length=3)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("listing", "From Listings"),
                            ("external", "External Source"),
                            ("survey", "Market Survey"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        default=1, help_text="Number of listings/data points"
                    ),
                ),
                ("recorded_date", models.DateField()),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="0-1, confidence in this price data",
                        max_digits=3,
                    ),
                ),
                (
                    "produce_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="listings.producetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Price",
                "verbose_name_plural": "Market Prices",
                "db_table": "market_prices",
                "ordering": ["-recorded_date"],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("district", models.CharField(blank=True, max_length=100)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("above", "Price Above"),
                            ("below", "Price Below"),
                            ("change", "Significant Change"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For 'change' alerts",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                (
                    "produce_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to="listings.producetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Alert",
                "verbose_name_plural": "Price Alerts",
                "db_table": "price_alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
