# Generated by Django 5.0.3 on 2026-05-08 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0002_initial"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pricealert",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricetrend",
            name="produce_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_trends",
                to="listings.producetype",
            ),
        ),
        migrations.AddIndex(
            model_name="marketprice",
            index=models.Index(
                fields=["produce_type", "district", "-recorded_date"],
                name="market_pric_produce_5b71d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketprice",
            index=models.Index(
                fields=["recorded_date"], name="market_pric_recorde_e77dc0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketprice",
            unique_together={("produce_type", "district", "recorded_date")},
        ),
        migrations.AddIndex(
            model_name="pricealert",
            index=models.Index(
                fields=["user", "is_active"], name="price_alert_user_id_600b95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricealert",
            index=models.Index(
                fields=["produce_type", "is_active"],
                name="price_alert_produce_de9407_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricetrend",
            index=models.Index(
                fields=["produce_type", "-period_end"],
                name="price_trend_produce_6b8a1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricetrend",
            index=models.Index(
                fields=["district", "-period_end"],
                name="price_trend_distric_5616ee_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricetrend",
            unique_together={
                ("produce_type", "district", "period_start", "period_end")
            },
        ),
    ]
