# Generated by Django 5.0.3 on 2026-05-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("farm_name", models.CharField(blank=True, max_length=255)),
                (
                    "farm_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Farm size in selected unit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "farm_size_unit",
                    models.CharField(
                        choices=[("hectares", "Hectares"), ("acres", "Acres")],
                        default="hectares",
                        max_length=20,
                    ),
                ),
                ("farm_description", models.TextField(blank=True, max_length=1000)),
                (
                    "primary_crops",
                    models.JSONField(
                        default=list, help_text="List of primary crop types"
                    ),
                ),
                ("is_organic_certified", models.BooleanField(default=False)),
                ("certifications", models.JSONField(blank=True, default=list)),
                (
                    "farming_experience_years",
                    models.IntegerField(blank=True, null=True),
                ),
                ("total_listings", models.IntegerField(default=0)),
                ("active_listings", models.IntegerField(default=0)),
                ("successful_sales", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average rating from buyers (0-5)",
                        max_digits=3,
                    ),
                ),
                ("total_ratings", models.IntegerField(default=0)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_documents", models.JSONField(blank=True, default=list)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("badges", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Farmer Profile",
                "verbose_name_plural": "Farmer Profiles",
                "db_table": "farmer_profiles",
            },
        ),
        migrations.CreateModel(
            name="FarmerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("review", models.TextField(blank=True, max_length=500)),
                ("farmer_response", models.TextField(blank=True, max_length=500)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Farmer Rating",
                "verbose_name_plural": "Farmer Ratings",
                "db_table": "farmer_ratings",
                "ordering": ["-created_at"],
            },
        ),
    ]
