# Generated by Django 5.0.3 on 2026-05-08 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "0001_initial"),
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farmerrating",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farmerrating",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farmerrating",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.listing",
            ),
        ),
        migrations.AddIndex(
            model_name="farmerprofile",
            index=models.Index(
                fields=["verification_status"], name="farmer_prof_verific_6d87a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmerprofile",
            index=models.Index(
                fields=["-average_rating"], name="farmer_prof_average_681575_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmerprofile",
            index=models.Index(
                fields=["-total_listings"], name="farmer_prof_total_l_2602f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmerrating",
            index=models.Index(
                fields=["farmer", "-created_at"], name="farmer_rati_farmer__f02c65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmerrating",
            index=models.Index(fields=["rating"], name="farmer_rati_rating_a4c1f3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="farmerrating",
            unique_together={("farmer", "buyer", "listing")},
        ),
    ]
