# Generated by Django 5.0.3 on 2026-05-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfflineCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cache_key", models.CharField(max_length=255)),
                (
                    "cache_type",
                    models.CharField(
                        choices=[
                            ("listings", "Listings"),
                            ("messages", "Messages"),
                            ("prices", "Market Prices"),
                            ("profile", "Profile Data"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "data_hash",
                    models.CharField(
                        help_text="Hash of cached data for validation", max_length=64
                    ),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "offline_cache",
                "ordering": ["-last_accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("listing_create", "Create Listing"),
                            ("listing_update", "Update Listing"),
                            ("message_send", "Send Message"),
                            ("profile_update", "Update Profile"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "operation_id",
                    models.CharField(
                        help_text="Client-side operation ID", max_length=100
                    ),
                ),
                ("payload", models.JSONField(help_text="Data to be synced")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sync_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
