# Generated by Django 5.0.3 on 2026-05-08 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offlinecache",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offline_cache",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offlinecache",
            unique_together={("user", "cache_key")},
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["user", "status", "-created_at"],
                name="sync_logs_user_id_27fc9b_idx",
            ),
        ),
    ]
