# Generated by Django 5.0.3 on 2026-05-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuyerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(blank=True, max_length=255)),
                (
                    "buyer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("restaurant", "Restaurant"),
                            ("retailer", "Retailer"),
                            ("wholesaler", "Wholesaler"),
                            ("institution", "Institution"),
                            ("exporter", "Exporter"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("business_registration", models.CharField(blank=True, max_length=100)),
                ("business_description", models.TextField(blank=True, max_length=1000)),
                (
                    "preferred_categories",
                    models.JSONField(
                        default=list, help_text="Preferred produce categories"
                    ),
                ),
                (
                    "preferred_districts",
                    models.JSONField(
                        default=list, help_text="Preferred sourcing locations"
                    ),
                ),
                (
                    "preferred_delivery_method",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("delivery", "Delivery"),
                            ("both", "Both"),
                        ],
                        default="pickup",
                        max_length=20,
                    ),
                ),
                ("total_purchases", models.IntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("successful_transactions", models.IntegerField(default=0)),
                ("saved_listings_count", models.IntegerField(default=0)),
                ("followed_farmers_count", models.IntegerField(default=0)),
                (
                    "buyer_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
            ],
            options={
                "verbose_name": "Buyer Profile",
                "verbose_name_plural": "Buyer Profiles",
                "db_table": "buyer_profiles",
            },
        ),
        migrations.CreateModel(
            name="FollowedFarmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notify_new_listings", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Followed Farmer",
                "verbose_name_plural": "Followed Farmers",
                "db_table": "followed_farmers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "Saved Listing",
                "verbose_name_plural": "Saved Listings",
                "db_table": "saved_listings",
                "ordering": ["-created_at"],
            },
        ),
    ]
