# Generated by Django 5.0.3 on 2026-05-08 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="followedfarmer",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_farmers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="followedfarmer",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedlisting",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedlisting",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="listings.listing",
            ),
        ),
        migrations.AddIndex(
            model_name="followedfarmer",
            index=models.Index(fields=["buyer"], name="followed_fa_buyer_i_94653b_idx"),
        ),
        migrations.AddIndex(
            model_name="followedfarmer",
            index=models.Index(
                fields=["farmer"], name="followed_fa_farmer__4e1486_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="followedfarmer",
            unique_together={("buyer", "farmer")},
        ),
        migrations.AddIndex(
            model_name="savedlisting",
            index=models.Index(
                fields=["buyer", "-created_at"], name="saved_listi_buyer_i_adcf5b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedlisting",
            unique_together={("buyer", "listing")},
        ),
    ]
