# Generated by Django 5.0.3 on 2026-05-08 01:29

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Zimbabwe phone number format: +263...",
                        max_length=20,
                        unique=True,
                        validators=[
                            apps.core.validators.validate_zimbabwe_phone_number
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("farmer", "Farmer"),
                            ("buyer", "Buyer"),
                            ("admin", "Admin"),
                        ],
                        default="farmer",
                        max_length=10,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/%Y/%m/"
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(blank=True, null=True, upload_to="covers/%Y/%m/"),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("district", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        max_length=10,
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Token",
                "verbose_name_plural": "Device Tokens",
                "db_table": "device_tokens",
            },
        ),
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Phone Verification",
                "verbose_name_plural": "Phone Verifications",
                "db_table": "phone_verifications",
                "indexes": [
                    models.Index(
                        fields=["phone_number", "code"],
                        name="phone_verif_phone_n_ed033c_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="phone_verif_expires_efa46d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("push_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=False)),
                ("notify_new_messages", models.BooleanField(default=True)),
                ("notify_price_alerts", models.BooleanField(default=True)),
                ("notify_new_listings", models.BooleanField(default=True)),
                ("notify_inquiries", models.BooleanField(default=True)),
                ("notify_order_status", models.BooleanField(default=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("sn", "Shona"), ("nd", "Ndebele")],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("sync_on_wifi_only", models.BooleanField(default=True)),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                        ],
                        default="realtime",
                        max_length=20,
                    ),
                ),
                ("show_phone_number", models.BooleanField(default=False)),
                ("show_location", models.BooleanField(default=True)),
                ("allow_messages_from_anyone", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
                "db_table": "user_settings",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="users_phone_n_a3b1c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_type"], name="users_user_ty_578f8f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["district"], name="users_distric_66c301_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "user_type"], name="users_is_acti_e1f8d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["user", "is_active"], name="device_toke_user_id_e99165_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(fields=["token"], name="device_toke_token_e218ea_idx"),
        ),
    ]
