# Generated by Django 5.0.3 on 2026-05-08 01:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="listings/%Y/%m/%d/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="Size in bytes", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Image",
                "verbose_name_plural": "Listing Images",
                "db_table": "listing_images",
                "ordering": ["order", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="ListingView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Listing View",
                "verbose_name_plural": "Listing Views",
                "db_table": "listing_views",
            },
        ),
        migrations.CreateModel(
            name="ProduceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "common_units",
                    models.JSONField(
                        default=list, help_text="Common units: ['kg', 'tonnes', 'bags']"
                    ),
                ),
                (
                    "typical_price_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "typical_price_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Produce Type",
                "verbose_name_plural": "Produce Types",
                "db_table": "produce_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class or emoji", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="listings.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "listing_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Roma tomatoes, Yellow maize",
                        max_length=100,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Grade A, Premium, Export Quality, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "quantity_available",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilograms"),
                            ("g", "Grams"),
                            ("tonnes", "Tonnes"),
                            ("bags", "Bags"),
                            ("crates", "Crates"),
                            ("trays", "Trays"),
                            ("bundles", "Bundles"),
                            ("pieces", "Pieces"),
                            ("heads", "Heads"),
                            ("litres", "Litres"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "minimum_order",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum order quantity",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("currency", models.CharField(default="ZWL", max_length=3)),
                ("is_negotiable", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_organic", models.BooleanField(default=False)),
                (
                    "quality_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="['fresh', 'pesticide-free', 'locally-grown']",
                    ),
                ),
                ("farm_location", models.CharField(blank=True, max_length=255)),
                ("district", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("available_from", models.DateField()),
                ("available_until", models.DateField()),
                ("harvest_date", models.DateField(blank=True, null=True)),
                ("delivery_available", models.BooleanField(default=False)),
                ("delivery_radius_km", models.IntegerField(blank=True, null=True)),
                ("pickup_available", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("inquiry_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("save_count", models.IntegerField(default=0)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("version", models.IntegerField(default=1)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="listings.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
                "db_table": "listings",
                "ordering": ["-created_at"],
            },
        ),
    ]
