# Generated by Django 5.0.3 on 2026-05-08 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="listingview",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="listingview",
            name="viewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="producetype",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produce_types",
                to="listings.category",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="produce_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="listings.producetype"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="categories_slug_b4303a_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "order"], name="categories_is_acti_30b877_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingimage",
            index=models.Index(
                fields=["listing", "order"], name="listing_ima_listing_46e482_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingview",
            index=models.Index(
                fields=["listing", "-viewed_at"], name="listing_vie_listing_d8c931_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingview",
            index=models.Index(
                fields=["viewer", "-viewed_at"], name="listing_vie_viewer__2df503_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="producetype",
            unique_together={("category", "slug")},
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["farmer", "status"], name="listings_farmer__ddb0d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["category", "status"], name="listings_categor_7f7673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["produce_type", "status"], name="listings_produce_84901d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["district", "status"], name="listings_distric_b44457_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "-created_at"], name="listings_status_174ca4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-published_at"], name="listings_publish_33af56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["available_from", "available_until"],
                name="listings_availab_677b3a_idx",
            ),
        ),
    ]
